# NORMALIZATION PROBLEM

In [2]:
import numpy as np

In [30]:
X = np.random.random((5,5))
Z = (X - X.mean())/X.std()
np.save('X_normalized.npy', Z)

In [32]:
np.load('X_normalized.npy')

array([[-0.04981045, -1.07185517, -0.24283244,  0.75036447, -0.16201171],
       [ 0.64126235, -0.22249694,  0.8096391 ,  1.72523702, -1.2673554 ],
       [-0.90515824, -1.4179732 ,  0.00931478,  0.38485068, -1.28729553],
       [ 0.27343053,  0.54994795,  0.45704131,  1.56709102, -1.48709333],
       [-0.20553447, -1.40490689,  1.4216586 , -0.64359601,  1.77808198]])

# DIVISIBLE BY 3 PROBLEM

In [89]:
integers = np.arange(1,101)
squared_integers = integers**2
matrix = squared_integers.reshape(10,10)
divided_matrix_numbers = matrix[np.mod(matrix,3)==0]
divided_matrix_boolean = np.mod(matrix,3)==0
np.save('div_by_3', divided_matrix_numbers)
np.save('div_by_3_bool', divided_matrix_boolean)

In [95]:
np.load('div_by_3.npy')

array([   9,   36,   81,  144,  225,  324,  441,  576,  729,  900, 1089,
       1296, 1521, 1764, 2025, 2304, 2601, 2916, 3249, 3600, 3969, 4356,
       4761, 5184, 5625, 6084, 6561, 7056, 7569, 8100, 8649, 9216, 9801])

In [97]:
np.load('div_by_3_bool.npy')

array([[False, False,  True, False, False,  True, False, False,  True,
        False],
       [False,  True, False, False,  True, False, False,  True, False,
        False],
       [ True, False, False,  True, False, False,  True, False, False,
         True],
       [False, False,  True, False, False,  True, False, False,  True,
        False],
       [False,  True, False, False,  True, False, False,  True, False,
        False],
       [ True, False, False,  True, False, False,  True, False, False,
         True],
       [False, False,  True, False, False,  True, False, False,  True,
        False],
       [False,  True, False, False,  True, False, False,  True, False,
        False],
       [ True, False, False,  True, False, False,  True, False, False,
         True],
       [False, False,  True, False, False,  True, False, False,  True,
        False]])